---
dependencies:
  - {role: geerlingguy.repo-epel, when: use_geerlingguy_repo_epel | default(true)}

galaxy_info:
  role_name: boilerplate
  author: David Alger
  description: Boilerplate Config for RHEL / CentOS
  license: MIT
  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
        - 8
        - 7

  galaxy_tags:
    - system
