---
dependencies: []

galaxy_info:
  role_name: php_cachetool
  author: David Alger
  description: >
    Installs CacheTool for PHP allowing you to work with `apc`, `opcache`, etc the file status cache through the CLI.
  license: MIT
  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
        - 7
        - 6

  galaxy_tags:
    - system
    - cachetool
    - php
