---

# Download links and checksums found at https://getcomposer.org/download/
_composer_download:
  1.9.3:
    url: "https://getcomposer.org/download/1.9.3/composer.phar"
    dest: "/var/cache/ansible/composer-1.9.3.phar"
    checksum: "sha256:551655c2fc81f4106508f42bbc4b24eabd34b022b13bc1e7d9642bf483d0a7d4"
  1.9.1:
    url: "https://getcomposer.org/download/1.9.1/composer.phar"
    dest: "/var/cache/ansible/composer-1.9.1.phar"
    checksum: "sha256:1f210b9037fcf82670d75892dfc44400f13fe9ada7af9e787f93e50e3b764111"
  1.10.17:
    url: "https://getcomposer.org/download/1.10.17/composer.phar"
    dest: "/var/cache/ansible/composer-1.10.17.phar"
    checksum: "sha256:6fa00eba5103ce6750f94f87af8356e12cc45d5bbb11a140533790cf60725f1c"
  2.0.14:
    url: "https://getcomposer.org/download/2.0.14/composer.phar"
    dest: "/var/cache/ansible/composer-2.0.14.phar"
    checksum: "sha256:29454b41558968ca634bf5e2d4d07ff2275d91b637a76d7a05e6747d36dd3473"
  2.1.3:
    url: "https://getcomposer.org/download/2.1.3/composer.phar"
    dest: "/var/cache/ansible/composer-2.1.3.phar"
    checksum: "sha256:f8a72e98dec8da736d8dac66761ca0a8fbde913753e9a43f34112367f5174d11"
